import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../Components/Main'
import Navbar from '../Components/Navbar'
import Footer from '../Components/Footer'
import Testimonials from '../Components/Testimonials'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Pablo Di Pietro - Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
        <Main/>
        <Testimonials/>
      <Footer/>
    </div>
  )
}
